name: ci/cd pipeline
run-name: ${{ github.actor }} triggered ${{ name }} workflow via ${{ github.event_name}} event
on: 
  push:
    branches: 
      - main
jobs:
  check-code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./mvnw --version
