name: ci/cd pipeline
run-name: ${{ github.actor }} triggered ${{ github.workflow }} workflow via ${{ github.event_name}} event
on: 
  push:
    branches: 
      - main
jobs:
  cache-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - run: ./mvnw --version
      - run: ./mvnw -U -B dependency:go-offline # warm up maven cache, will not download absolute everything so '-o' not advised
  check-code-format:
    needs: cache-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - run: ./mvnw --version
      - run: echo ./mvnw -B fmt:check # disabled for now
      - run: java -version
  compile:
    needs: check-code-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: ./mvnw -B resources:resources compiler:compile
      - uses: actions/upload-artifact@v3
        with:
          name: Target
          path: target
          retention-days: 1
  unit-test:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Target
          path: target
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: ./mvnw -B resources:testResources compiler:testCompile surefire:test
      - uses: actions/upload-artifact@v3
        with:
          name: Target
          path: target
          retention-days: 1
  package:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Target
          path: target
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: ./mvnw -B jar:jar spring-boot:repackage
      - uses: actions/upload-artifact@v3
        with:
          name: Target
          path: target
          retention-days: 1
  publish:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO
  build-container:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO
  publish-container:
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO
  # post artifact tests could also be performed after package, not sure yet
  acceptance-test:
    needs: publish-container
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO
  performance-test:
    needs: publish-container
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO
  security-test:
    needs: publish-container
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO
  # deploy on int after or parallel to tests ???
  deploy-int:
    needs: acceptance-test # first draft, after successful acceptance tests
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO
  # first draft, deploy to live after all tests
  deploy-live:
    needs: 
      - acceptance-test
      - performance-test
      - security-test
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO

