name: ci/cd pipeline
run-name: ${{ github.actor }} triggered ${{ github.workflow }} workflow via ${{ github.event_name}} event
on: 
  push:
    branches: 
      - main
jobs:
  cache-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: find ~/.m2/repository/ -name "*.jar" | wc -l
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - run: find ~/.m2/repository/ -name "*.jar" | wc -l
      - run: ./mvnw --version
      - run: ./mvnw -U -B dependency:go-offline # warm up maven cache
      - run: find ~/.m2/repository/ -name "*.jar" | wc -l
  check-code-format:
    needs: cache-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - run: ./mvnw --version
      - run: echo ./mvnw -o -B fmt:check # disabled for now
      - run: java -version
  compile:
    needs: check-code-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: find ~/.m2/repository/ -name "*.jar" | wc -l
      - run: ./mvnw -o -B resources:resources compiler:compile
      - run: ls -lash target
      - uses: actions/upload-artifact@v3
        with:
          name: Target
          path: target
          retention-days: 1
  unit-test:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - run: ls -lash
      - uses: actions/checkout@v3
      - run: ls -lash
      - uses: actions/download-artifact@v3
        with:
          name: Target
          path: target
      - run: ls -lash
      - run: ls -lash target
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: find ~/.m2/repository/ -name "*.jar" | wc -l
      - run: ls -lash target
      - run: ./mvnw -o -B resources:testResources compiler:testCompile surefire:test
      - run: ls -lash target
      - uses: actions/upload-artifact@v3
        with:
          name: Target
          path: target
          retention-days: 1
  package:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Target
          path: target
      - run: ls -lash target
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: find ~/.m2/repository/ -name "*.jar" | wc -l
      - run: ./mvnw -o -B jar:jar spring-boot:repackage
      - run: ls -lash target
      - uses: actions/upload-artifact@v3
        with:
          name: Target
          path: target
          retention-days: 1
